import React, { createContext, useContext, useState, useEffect, useRef } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LanguageContext = createContext();

const translations = {
  gu: {
    'Trade': 'વેપાર',
    'Non-Trade': 'નોન-ટ્રેડ',
    'Search Retailers...': 'રિટેલર્સ શોધો...',
    'Retailers': 'રિટેલર્સ',
    'Retailer Directory': 'રિટેલર ડિરેક્ટરી',
    'Search Orders...': 'ઓર્ડર શોધો...',
    'History': 'ઇતિહાસ',

    'Place Order': 'ઓર્ડર આપો',
    'Financial Overview': 'નાણાકીય વિહંગાવલોકન',
    'Available Balance': 'ઉપલબ્ધ બેલેન્સ',
    'Total': 'કુલ',
    'Submitted': 'સબમિટ કરેલ',
    'Invoices': 'ઇન્વોઇસેસ',
    'Order Trends (Past ': 'ઓર્ડર વલણો (છેલ્લા ',
    ' Days)': ' દિવસ)',
    'Credit Utilization': 'ક્રેડિટ નો ઉપયોગ',
    'Spendable': 'ખર્ચવાપાત્ર',
    'Limit': 'મર્યાદા',
    'Limit:': 'મર્યાદા:',
    'Outstanding:': 'બાકી:',
    'Spendable:': 'ખર્ચવાપાત્ર:',
    'Ageing & Actions': 'એજિંગ અને ક્રિયાઓ',
    'Overdue Payments': 'બાકી ચૂકવણી',
    'Immediate attention required': 'તાત્કાલિક ધ્યાન જરૂરી છે',
    'Due Today': 'આજે બાકી',
    'Payments scheduled for today': 'આજે માટે સુનિશ્ચિત ચૂકવણી',
    'Support Contacts': 'આધાર સંપર્કો',
    'Sales Representative': 'વેચાણ પ્રતિનિધિ',
    'System Admin': 'સિસ્ટમ એડમિન',
    'Rewards Progress': 'ઇનામોની પ્રગતિ',
    'Tons (Target 1)': 'ટન (લક્ષ્ય 1)',
    'Tons (Target 2)': 'ટન (લક્ષ્ય 2)',
    'Target 1 Progress (': 'લક્ષ્ય 1 પ્રગતિ (',
    '%)': '%)',
    'Target 2 Progress (': 'લક્ષ્ય 2 પ્રગતિ (',
    'Select Date Range': 'તારીખ રેન્જ પસંદ કરો',
    'Cancel': 'રદ કરો',
    'Past 7 Days': 'છેલ્લા 7 દિવસ',
    'Past 30 Days': 'છેલ્લા 30 દિવસ',
    'Above 21 Days': '21 દિવસથી ઉપર',
    'Hi,': 'નમસ્તે,',

    'Rewards': 'ઇનામો',
    'Segment (Trade / Non-Trade)': 'વિભાગ (ટ્રેડ / નોન-ટ્રેડ)',
    'All Segments': 'બધા સેગમેન્ટ્સ',
    'Sales Assignments': 'સેલ્સ અસાઇનમેન્ટ્સ',
    'Sales Visits': 'સેલ્સ મુલાકાતો',
    'Role Access Control': 'રોલ એક્સેસ કંટ્રોલ',
    'Create Member': 'સભ્ય બનાવો',
    'Create Member Account': 'સભ્ય એકાઉન્ટ બનાવો',
    'Creating Member...': 'સભ્ય બનાવી રહ્યા છીએ...',
    'Unknown Retailer': 'અજાણ્યો રિટેલર',
    'No Company': 'કોઈ કંપની નથી',
    'Sales Rejected': 'સેલ્સ નકારી કાઢ્યું',
    'Admin Rejected': 'એડમિન નકારી કાઢ્યું',
    'Active': 'સક્રિય',
    'Blocked': 'અવરોધિત',
    'orders': 'ઓર્ડર્સ',
    'payments': 'ચુકવણીઓ',
    'challans': 'ચલણો',
    'dealer': 'ડીલર',
    'retailer': 'રિટેલર',
    'users': 'વપરાશકર્તાઓ',
    'assignments': 'અસાઇનમેન્ટ્સ',
    'visits': 'મુલાકાતો',
    'create': 'બનાવો',
    'Report exported successfully!': 'રિપોર્ટ સફળતાપૂર્વક નિકાસ થયો!',
    'Error': 'ભૂલ',
    'Failed to load products': 'ઉત્પાદનો લોડ કરવામાં નિષ્ફળ',
    'Success': 'સફળતા',
    'Zone mappings saved successfully': 'ઝોન મેપિંગ્સ સફળતાપૂર્વક સાચવ્યા',
    'Failed to save mappings': 'મેપિંગ્સ સાચવવામાં નિષ્ફળ',
    'Product Name is required.': 'ઉત્પાદનનું નામ જરૂરી છે.',
    'Failed to add product': 'ઉત્પાદન ઉમેરવામાં નિષ્ફળ',
    'Failed to update product': 'ઉત્પાદન અપડેટ કરવામાં નિષ્ફળ',
    'Confirm': 'ખાતરી કરો',
    'Are you sure you want to delete this product?': 'શું તમે ખરેખર આ ઉત્પાદન કાઢી નાખવા માંગો છો?',
    'Failed to delete product': 'ઉત્પાદન કાઢી નાખવામાં નિષ્ફળ',
    'Base price must be greater than 0.': 'મૂળ કિંમત 0 થી વધુ હોવી જોઈએ.',
    'Ahmedabad Base Price saved successfully!': 'અમદાવાદ મૂળ કિંમત સફળતાપૂર્વક સાચવી!',
    'Failed to save base price': 'મૂળ કિંમત સાચવવામાં નિષ્ફળ',
    'Failed to update formula': 'ફોર્મ્યુલા અપડેટ કરવામાં નિષ્ફળ',
    'Failed to update availability': 'ઉપલબ્ધતા અપડેટ કરવામાં નિષ્ફળ',
    'Failed to add grade': 'ગ્રેડ ઉમેરવામાં નિષ્ફળ',
    'Confirm Delete': 'કાઢી નાખવાની ખાતરી કરો',
    'Failed to delete grade': 'ગ્રેડ કાઢી નાખવામાં નિષ્ફળ',
    'Name, Email, Password, and Phone are required.': 'નામ, ઇમેઇલ, પાસવર્ડ અને ફોન જરૂરી છે.',
    'Phone number must be at least 10 digits.': 'ફોન નંબર ઓછામાં ઓછા 10 અંકોનો હોવો જોઈએ.',
    'User created successfully!': 'વપરાશકર્તા સફળતાપૂર્વક બનાવવામાં આવ્યો!',
    'Failed to load data': 'ડેટા લોડ કરવામાં નિષ્ફળ',
    'Please select a dealer.': 'કૃપા કરીને ડીલર પસંદ કરો.',
    'Quantity must be greater than 0.': 'જથ્થો 0 થી વધુ હોવો જોઈએ.',
    'Challan logged successfully': 'ચલણ સફળતાપૂર્વક લોગ થયું',
    'Failed to load customers': 'ગ્રાહકોને લોડ કરવામાં નિષ્ફળ',
    'Credit limit cannot be negative.': 'ક્રેડિટ લિમિટ નકારાત્મક ન હોઈ શકે.',
    'Download Error': 'ડાઉનલોડ ભૂલ',
    'Failed to load documents for this customer': 'આ ગ્રાહક માટે દસ્તાવેજો લોડ કરવામાં નિષ્ફળ',
    'Preview Error': 'પૂર્વાવલોકન ભૂલ',
    'Reading and parsing Excel file...': 'એક્સેલ ફાઇલ વાંચી અને પાર્સ કરી રહ્યા છીએ...',
    'This import type is not yet fully implemented.': 'આ આયાત પ્રકાર હજુ સંપૂર્ણપણે અમલમાં નથી.',
    'Failed to parse the Excel file.': 'એક્સેલ ફાઇલને પાર્સ કરવામાં નિષ્ફળ.',
    'Failed to load pending registrations': 'બાકી નોંધણીઓ લોડ કરવામાં નિષ્ફળ',
    'Hi,': 'નમસ્તે,',
    'Overall Information': 'એકંદર માહિતી',
    'Total Orders': 'કુલ ઓર્ડર્સ',
    'Overdue accounts': 'બાકી એકાઉન્ટ્સ',
    'PENDING': 'પેન્ડિંગ',
    'TRANSIT': 'ટ્રાન્ઝિટ',
    'COMPLETED': 'પૂર્ણ',
    'Orders': 'ઓર્ડર્સ',
    'Dispatch': 'ડિસ્પેચ',
    'Operational SLA': 'ઓપરેશનલ SLA',
    'compared to last month': 'ગયા મહિનાની સરખામણીમાં',
    'Download Report': 'રિપોર્ટ ડાઉનલોડ કરો',
    'Order Funnel:': 'ઓર્ડર ફનેલ:',
    'Submitted Orders': 'સબમિટ કરેલા ઓર્ડર્સ',
    'Approved Orders': 'મંજૂર ઓર્ડર્સ',
    'Delivered & Closed': 'વિતરિત અને બંધ',
    'Exceptions / Overdue': 'અપવાદો / બાકી',
    'Sort by': 'ક્રમમાં ગોઠવો',
    'In progress': 'પ્રગતિમાં',
    'Total Sales:': 'કુલ વેચાણ:',
    'Orders:': 'ઓર્ડર્સ:',
    '+ View All Reps': '+ બધા રેપ્સ જુઓ',
    'No orders pending your approval.': 'તમારી મંજૂરી માટે કોઈ ઓર્ડર બાકી નથી.',
    'x': 'x',
    'Review': 'સમીક્ષા કરો',
    'View all': 'બધા જુઓ',
    'pending orders': 'બાકી ઓર્ડર્સ',
    'Retailer Directory': 'રિટેલર ડિરેક્ટરી',
    'Pricing': 'કિંમત નિર્ધારણ',
    'Zone Rates Pricing Matrix': 'ઝોન દર કિંમત મેટ્રિક્સ',
    'e.g. 300': 'દા.ત. 300',
    'Formula': 'ફોર્મ્યુલા',
    '/ ton': '/ ટન',
    'Enter Grade (e.g. OPC53)': 'ગ્રેડ દાખલ કરો (દા.ત. OPC53)',
    'Sales Rep:': 'સેલ્સ રેપ:',
    'Search Order ID...': 'ઓર્ડર ID શોધો...',
    'All Time': 'તમામ સમય',
    'Today': 'આજે',
    'Yesterday': 'ગઈકાલે',
    'Last 7 Days': 'છેલ્લા 7 દિવસ',
    'Explain rejection reason...': 'અસ્વીકાર કરવાનું કારણ સમજાવો...',
    'Search...': 'શોધો...',
    'ID:': 'ID:',
    'MTD Vol:': 'MTD વોલ્યુમ:',
    '/ 250 Tons': '/ 250 ટન',
    'Customer / Retailer': 'ગ્રાહક / રિટેલર',
    'Sales Representative': 'વેચાણ પ્રતિનિધિ',
    'Accountant': 'એકાઉન્ટન્ટ',
    'Administrator': 'સંચાલક',
    '-- Unassigned --': '-- અસાઇન કરેલ નથી --',
    'Retailer ID:': 'રિટેલર ID:',
    'Customer / Dealer': 'ગ્રાહક / ડીલર',
    '- Select District -': '- જિલ્લો પસંદ કરો -',
    'Search ID, Company...': 'ID, કંપની શોધો...',
    'Select Dealer': 'ડીલર પસંદ કરો',
    'YYYY-MM-DD': 'YYYY-MM-DD',
    'Main Godown': 'મુખ્ય ગોડાઉન',
    'Kathwada': 'કઠવાડા',
    'Bhakrol': 'ભાકરોલ',
    'Aslali': 'અસલાલી',
    'OPC': 'OPC',
    'BPC': 'BPC',
    'Plus': 'પ્લસ',
    'e.g. 100': 'દા.ત. 100',
    'Search customers...': 'ગ્રાહકો શોધો...',
    'Aadhar Card': 'આધાર કાર્ડ',
    'PAN Card': 'પાન કાર્ડ',
    'GST Certificate': 'GST પ્રમાણપત્ર',
    'Company PAN': 'કંપની PAN',
    'Bank Cheque': 'બેંક ચેક',
    '\'s registration. This will be shown to the customer.': 'નું રજીસ્ટ્રેશન. આ ગ્રાહકને બતાવવામાં આવશે.',
    'Volume Trends (7d)': 'વોલ્યુમ ટ્રેન્ડ્સ (7d)',
    'Active (': 'સક્રિય (',
    'Delayed (': 'વિલંબિત (',
    'Blocked (': 'અવરોધિત (',
    'Top Sales Reps (': 'ટોચના સેલ્સ રેપ્સ (',
    'Pending Admin Approvals (': 'બાકી એડમિન મંજૂરીઓ (',
    '(ID:': '(ID:',
    'Please select the reason(s) for rejecting': 'કૃપા કરીને અસ્વીકાર કરવા માટેના કારણો પસંદ કરો',
    'Trade': 'વેપાર',
    'Non-Trade': 'નોન-ટ્રેડ',
    'Import Customers': 'ગ્રાહકો આયાત કરો',
    'Import Customer Rewards': 'ગ્રાહક ઇનામો આયાત કરો',
    'Import Inventory': 'ઇન્વેન્ટરી આયાત કરો',
    'Import Invoices': 'ઇન્વોઇસ આયાત કરો',
    'Import Orders': 'ઓર્ડર્સ આયાત કરો',
    'Import customer details and create accounts.': 'ગ્રાહકની વિગતો આયાત કરો અને એકાઉન્ટ બનાવો.',
    'Assign reward targets based on Cust Num.': 'કસ્ટમર નંબરના આધારે ઇનામ લક્ષ્ય સેટ કરો.',
    'Update products and stock levels (Coming Soon)': 'ઉત્પાદનો અને સ્ટોક અપડેટ કરો (ટૂંક સમયમાં)',
    'Import generated invoices (Coming Soon)': 'જનરેટ થયેલ ઇન્વોઇસ આયાત કરો (ટૂંક સમયમાં)',
    'Bulk import previous orders (Coming Soon)': 'અગાઉના ઓર્ડર બલ્ક આયાત કરો (ટૂંક સમયમાં)',
    'Customer:': 'ગ્રાહક:',
    'Amount:': 'રકમ:',
    'Payment Info:': 'ચુકવણી માહિતી:',
    'Pending': 'બાકી',
    'View Invoice': 'ઇન્વોઇસ જુઓ',
    'No Invoice Yet': 'હજુ કોઈ ઇન્વોઇસ નથી',
    'Receipt': 'રસીદ',
    'Payment Receipt': 'ચુકવણી રસીદ',
    'No receipt available': 'કોઈ રસીદ ઉપલબ્ધ નથી',
    'All Invoices': 'બધા ઇન્વોઇસ',
    'View and search all invoices generated across the system.': 'સિસ્ટમમાં જનરેટ થયેલ તમામ ઇન્વોઇસ જુઓ અને શોધો.',
    'No Invoices Yet': 'હજુ કોઈ ઇન્વોઇસ નથી',
    'Product:': 'ઉત્પાદન:',
    'Due Date:': 'નિયત તારીખ:',
    'Invoice Amount:': 'ઇન્વોઇસ રકમ:',
    'View Receipt': 'રસીદ જુઓ',
    'Verify & Close': 'ચકાસો અને બંધ કરો',
    'Confirm': 'ખાતરી કરો',
    'Credit Cycles': 'ક્રેડિટ સાયકલ',
    'Tracking overdue and pending payments.': 'બાકી ચૂકવણીઓ ટ્રેકિંગ.',
    'Total Outstanding': 'કુલ બાકી',
    'Awaiting Verification': 'ચકાસણીની રાહ જોવાય છે',
    'No active credit records found.': 'કોઈ સક્રિય ક્રેડિટ રેકોર્ડ મળ્યા નથી.',
    'Edit Invoice Amount': 'ઇન્વોઇસ રકમ સંપાદિત કરો',
    'New Amount (₹)': 'નવી રકમ (₹)',
    'Save Changes': 'ફેરફારો સાચવો',
    'Quantity:': 'જથ્થો:',
    'Estimate Amount:': 'અંદાજિત રકમ:',
    'Upload Invoice': 'ઇન્વોઇસ અપલોડ કરો',
    'Pending Invoices': 'બાકી ઇન્વોઇસ',
    'Upload tax invoices for delivered orders.': 'વિતરિત ઓર્ડર માટે ટેક્સ ઇન્વોઇસ અપલોડ કરો.',
    'No pending invoices found.': 'કોઈ બાકી ઇન્વોઇસ મળ્યા નથી.',
    'Final Invoiced Amount (₹)': 'અંતિમ ઇન્વોઇસ રકમ (₹)',
    'Invoice PDF': 'ઇન્વોઇસ PDF',
    'Submit Invoice': 'ઇન્વોઇસ સબમિટ કરો',
    'Inventory & Pricing': 'ઇન્વેન્ટરી અને કિંમત',
    'Manage the product catalog available for ordering.': 'ઓર્ડર કરવા માટે ઉપલબ્ધ ઉત્પાદન સૂચિ મેનેજ કરો.',
    'Product Name': 'ઉત્પાદન નામ',
    'Grade (optional)': 'ગ્રેડ (વૈકલ્પિક)',
    'Save': 'સાચવો',
    'Set the Base Price (X) for Ahmedabad below. The matrix will automatically calculate prices for all other zones.': 'અમદાવાદ માટે બેઝ કિંમત સેટ કરો. મેટ્રિક્સ અન્ય ઝોન માટે કિંમતોની ગણતરી કરશે.',
    'Ahmedabad Base Price (X)': 'અમદાવાદ બેઝ કિંમત (X)',
    'Save Base Price': 'બેઝ કિંમત સાચવો',
    'Grade': 'ગ્રેડ',
    'Available': 'ઉપલબ્ધ',
    'Add New Grade': 'નવો ગ્રેડ ઉમેરો',
    'Product Overrides': 'ઉત્પાદન ઓવરરાઇડ્સ',
    'If manual prices are set here, they will override the matrix calculations.': 'જો મેન્યુઅલ કિંમતો સેટ કરેલ હોય, તો તે મેટ્રિક્સ ગણતરીઓને ઓવરરાઇડ કરશે.',
    'Price / Bag': 'કિંમત / બેગ',
    'Price / Ton': 'કિંમત / ટન',
    'Zone Configuration': 'ઝોન રૂપરેખાંકન',
    'Map districts to their respective zones. Separate multiple districts with a comma.': 'જિલ્લાઓને તેમના ઝોન સાથે મેપ કરો. અલ્પવિરામથી અલગ કરો.',
    'ORDER REQUEST': 'ઓર્ડર વિનંતી',
    'CLIENT INFO': 'ગ્રાહકની માહિતી',
    'PRODUCT TYPE': 'ઉત્પાદન પ્રકાર',
    'QUANTITY': 'જથ્થો',
    'EST. AMOUNT': 'અંદાજિત રકમ',
    'DESTINATION': 'ગંતવ્ય',
    'NOTES': 'નોંધો',
    'Customer Profile': 'ગ્રાહક પ્રોફાઇલ',
    'Total': 'કુલ',
    'On Time': 'સમયસર',
    'Overdue': 'બાકી',
    'EDIT': 'સંપાદિત કરો',
    'REJECT': 'નકારો',
    'APPROVE': 'મંજૂર કરો',
    'Final Approval Queue': 'અંતિમ મંજૂરી કતાર',
    'REJECT REQUEST': 'વિનંતી નકારો',
    'REASON': 'કારણ',
    'CANCEL': 'રદ કરો',
    'Team & Assignments': 'ટીમ અને કાર્યો',
    'Manage user access roles and territory sales representative assignments.': 'વપરાશકર્તા એક્સેસ ભૂમિકાઓ અને પ્રદેશ કાર્યોનું સંચાલન કરો.',
    'Access Role': 'એક્સેસ રોલ',
    'No users found.': 'કોઈ વપરાશકર્તા મળ્યા નથી.',
    'Assigned Sales Rep': 'સોંપાયેલ સેલ્સ પ્રતિનિધિ',
    'No customers found.': 'કોઈ ગ્રાહકો મળ્યા નથી.',
    'No visits found.': 'કોઈ મુલાકાતો મળી નથી.',
    'Create New Member': 'નવો સભ્ય બનાવો',
    'Full Name': 'પૂરું નામ',
    'Email (Login ID)': 'ઇમેઇલ (લોગિન ID)',
    'Password': 'પાસવર્ડ',
    'Role': 'ભૂમિકા',
    'Customer Details': 'ગ્રાહકની વિગતો',
    'Company Name': 'કંપનીનું નામ',
    'Phone Number': 'ફોન નંબર',
    'City': 'શહેર',
    'District': 'જિલ્લો',
    'Tehsil (Optional)': 'તાલુકો (વૈકલ્પિક)',
    'Full Address': 'પૂરું સરનામું',
    'CUSTOMER': 'ગ્રાહક',
    'PRODUCT': 'ઉત્પાદન',
    'UNIT PRICE': 'યુનિટ કિંમત',
    'ESTIMATE AMOUNT': 'અંદાજિત રકમ',
    'Edit Order': 'ઓર્ડર સંપાદિત કરો',
    'All Orders Directory': 'બધા ઓર્ડર ડિરેક્ટરી',
    'Complete ledger of all orders across the system.': 'સિસ્ટમમાં તમામ ઓર્ડર્સનું સંપૂર્ણ લેજર.',
    'No orders found.': 'કોઈ ઓર્ડર મળ્યા નથી.',
    'Challan & Deposit Tracking': 'ચલણ અને ડિપોઝિટ ટ્રેકિંગ',
    'Log New Challan': 'નવું ચલણ નોંધો',
    'Dealer / Party': 'ડીલર / પાર્ટી',
    'Date': 'તારીખ',
    'Depot': 'ડેપો',
    'Qty Deposited': 'જમા કરેલ જથ્થો',
    'Log Challan': 'ચલણ નોંધો',
    'Challan Log': 'ચલણ લોગ',
    'Quantity': 'જથ્થો',
    'No challans found': 'કોઈ ચલણ મળ્યા નથી',
    'Credit & Account Management': 'ક્રેડિટ અને એકાઉન્ટ મેનેજમેન્ટ',
    'Issue Overdue Penalties': 'પેનલ્ટી જારી કરો',
    'Segment': 'વિભાગ',
    'Non-Trade Access': 'નોન-ટ્રેડ એક્સેસ',
    'Credit Limit (₹)': 'ક્રેડિટ મર્યાદા (₹)',
    'Allowed Days': 'માન્ય દિવસો',
    'Outstanding': 'બાકી',
    'Unlock Account': 'એકાઉન્ટ અનલૉક કરો',
    'Revoke Unlock': 'અનલૉક રદ કરો',
    'APPROVED': 'મંજૂર',
    'Email': 'ઇમેઇલ',
    'Phone': 'ફોન',
    'GSTIN': 'GSTIN',
    'Attached Documents': 'જોડાયેલા દસ્તાવેજો',
    'No documents uploaded.': 'કોઈ દસ્તાવેજો અપલોડ કર્યા નથી.',
    'Load Documents': 'દસ્તાવેજો લોડ કરો',
    'Customer Documents': 'ગ્રાહક દસ્તાવેજો',
    'View submitted documents': 'સબમિટ કરેલા દસ્તાવેજો જુઓ',
    'No Customers Found': 'કોઈ ગ્રાહકો મળ્યા નથી',
    'Process Ongoing': 'પ્રક્રિયા ચાલુ છે',
    'Please do not close this window until the import is complete.': 'આયાત પૂર્ણ ન થાય ત્યાં સુધી આ વિન્ડો બંધ કરશો નહીં.',
    'Data Import Hub': 'ડેટા આયાત હબ',
    'Bulk import your data using Excel spreadsheets': 'એક્સેલનો ઉપયોગ કરીને ડેટા બલ્ક આયાત કરો',
    'Outstanding Notes': 'બાકી નોંધો',
    'Log of all manual adjustments to outstanding balances and their mandatory reasons.': 'મેન્યુઅલ એડજસ્ટમેન્ટ અને કારણોનો લોગ.',
    'No Outstanding Notes Yet': 'હજુ કોઈ નોંધો નથી',
    'Manual adjustments will appear here.': 'મેન્યુઅલ એડજસ્ટમેન્ટ અહીં દેખાશે.',
    'Pending Registrations': 'પેન્ડિંગ નોંધણી',
    'Review and approve new retailer accounts': 'નવા ખાતાઓની સમીક્ષા કરો',
    'All Caught Up!': 'બધું પૂર્ણ!',
    'There are no pending registrations at the moment.': 'હાલમાં કોઈ પેન્ડિંગ નોંધણી નથી.',
    'Reject Registration': 'નોંધણી નકારો',
    'Cancel': 'રદ કરો',
    'PM': 'PM',
    'PARAM MARKETING': 'પરમ માર્કેટિંગ',
    'Param Distributor Management': 'પરમ ડિસ્ટ્રીબ્યુટર મેનેજમેન્ટ',
    'Email or Customer ID': 'ઇમેઇલ અથવા કસ્ટમર ID',
    'Sign Out': 'સાઇન આઉટ',
    'Reason for Rejection:': 'નકારવાનું કારણ:',
    'Re-upload Documents': 'દસ્તાવેજો ફરીથી અપલોડ કરો',
    'Upload the corrected files below and resubmit your registration for review.': 'ફાઇલો અપલોડ કરો અને ફરીથી સબમિટ કરો.',
    'Invoices & Payments': 'ઇન્વોઇસ અને ચુકવણીઓ',
    'Track payments for your delivered orders.': 'તમારા ઓર્ડર માટે ચુકવણી ટ્રૅક કરો.',
    'You don\'t have any pending or closed invoices.': 'કોઈ ઇન્વોઇસ નથી.',
    'Amount': 'રકમ',
    'Pay Now': 'હવે ચૂકવો',
    'Submit Payment': 'ચુકવણી સબમિટ કરો',
    'PAYMENT FOR': 'ચુકવણી',
    'Transaction ID (UTR)': 'ટ્રાન્ઝેક્શન ID (UTR)',
    'Upload Receipt Screenshot': 'રસીદ સ્ક્રીનશોટ અપલોડ કરો',
    'Remove': 'દૂર કરો',
    'Tap to pick image': 'ઇમેજ પસંદ કરો',
    'JPEG, PNG, JPG': 'JPEG, PNG, JPG',
    'Transaction Details': 'ટ્રાન્ઝેક્શન વિગતો',
    'ID:': 'ID:',
    'Order Rejected': 'ઓર્ડર નકારાયો',
    'Under Process': 'પ્રક્રિયા હેઠળ',
    'Loading': 'લોડ કરી રહ્યાં છે',
    'Transit': 'ટ્રાન્ઝિટ',
    'Delivered': 'વિતરિત',
    'Invoice': 'ઇન્વોઇસ',
    'Confirm Receipt': 'રસીદની પુષ્ટિ કરો',
    'Verify Delivery': 'ડિલિવરી ચકાસો',
    'Raise Issue': 'સમસ્યા જણાવો',
    'Mark Complete': 'પૂર્ણ તરીકે માર્ક કરો',
    'Total Incurred': 'કુલ ખર્ચ',
    'Active': 'સક્રિય',
    'Dispatched': 'રવાના',
    'Filter by Date': 'તારીખ દ્વારા ફિલ્ટર કરો',
    'to': 'થી',
    'No Orders Found': 'કોઈ ઓર્ડર મળ્યો નથી',
    'You don\'t have any orders matching these filters.': 'કોઈ ઓર્ડર મળતો નથી.',
    'Place New Order': 'નવો ઓર્ડર આપો',
    'Account Details': 'એકાઉન્ટ વિગતો',
    'Company / Business': 'કંપની / વ્યવસાય',
    'Location / Region': 'સ્થાન / પ્રદેશ',
    'Edit Profile': 'પ્રોફાઇલ સંપાદિત કરો',
    'Report & Track Issues': 'સમસ્યાઓ અને ટ્રેક',
    'File disputes for orders and track their resolution status.': 'ઓર્ડર વિવાદ ફાઇલ કરો અને ટ્રેક કરો.',
    'File New Issue': 'નવી સમસ્યા ફાઇલ કરો',
    'My Past Reports': 'મારા જૂના રિપોર્ટ્સ',
    'Select Order': 'ઓર્ડર પસંદ કરો',
    'Issue Type': 'સમસ્યાનો પ્રકાર',
    'Describe the Issue': 'સમસ્યાનું વર્ણન કરો',
    'Affected Quantity (Bags/Units)': 'અસરગ્રસ્ત જથ્થો',
    'Photo Evidence': 'ફોટો પુરાવા',
    'Submit Report': 'રિપોર્ટ સબમિટ કરો',
    'No reports found for this period.': 'કોઈ રિપોર્ટ્સ મળ્યા નથી.',
    'View Details & Photo': 'વિગતો જુઓ',
    'Order ID': 'ઓર્ડર ID',
    'Date Reported': 'રિપોર્ટ કરેલ તારીખ',
    'Admin Notes': 'એડમિન નોંધો',
    'No notes yet.': 'હજુ કોઈ નોંધ નથી.',
    'Evidence': 'પુરાવા',
    'Order Placement Blocked': 'ઓર્ડર બ્લૉક કરેલ છે',
    'Go to Invoices': 'ઇન્વોઇસ પર જાઓ',
    'CLEAR': 'સાફ કરો',
    'LAST ORDER INFO': 'છેલ્લી ઓર્ડર માહિતી',
    'AUTOFILL': 'ઑટોફિલ',
    'Custom Site Delivery': 'કસ્ટમ સાઇટ ડિલિવરી',
    'Deliver to a location other than default address.': 'ડિફોલ્ટ સરનામાં સિવાયના સ્થાન પર વિતરિત કરો.',
    'Site Street Address': 'સાઇટ સરનામું',
    'State': 'રાજ્ય',
    'ZIP Code (Optional)': 'પિન કોડ',
    'Special Instructions (Optional)': 'ખાસ સૂચનાઓ',
    'Voice Note (Optional)': 'વૉઇસ નોંધ',
    'Voice Note Recorded': 'વૉઇસ નોંધ રેકોર્ડ કરી',
    'Stop Recording...': 'રેકોર્ડિંગ બંધ કરો...',
    'Record Audio Instructions': 'ઑડિઓ સૂચનાઓ રેકોર્ડ કરો',
    'Select Product Catalog': 'પ્રોડક્ટ પસંદ કરો',
    'Qty Required': 'જરૂરી જથ્થો',
    'Estimated Cost': 'અંદાજિત કિંમત',
    'SUBMIT PROCUREMENT REQUEST': 'ઓર્ડર સબમિટ કરો',
    'Rewards & Targets': 'ઇનામો અને લક્ષ્યો',
    'Track your campaign progress and unlock rewards': 'તમારી પ્રગતિ ટ્રૅક કરો',
    'TONS PROGRESS (TARGET 1)': 'પ્રગતિ (લક્ષ્ય 1)',
    'CAMPAIGN ENDS': 'અભિયાન સમાપ્ત થાય છે',
    'Unlocked': 'અનલૉક કરેલ',
    'TONS PROGRESS (TARGET 2)': 'પ્રગતિ (લક્ષ્ય 2)',
    'Your Rewards': 'તમારા ઇનામો',
    'Competitor Intel Feed': 'હરીફ માહિતી',
    'No competitor intel logged yet.': 'કોઈ હરીફ માહિતી નોંધાઈ નથી.',
    'View Image': 'ઇમેજ જુઓ',
    'Log Competitor Intel': 'હરીફ માહિતી નોંધો',
    'Photo Capture': 'ફોટો કેપ્ચર',
    'Tap to upload photo': 'ફોટો અપલોડ કરવા ટૅપ કરો',
    'Competitor Brand Name': 'હરીફ બ્રાન્ડ નામ',
    'Current Rate per Bag (₹)': 'વર્તમાન દર પ્રતિ બેગ',
    'Additional Notes': 'વધારાની નોંધો',
    'Submit Intel': 'માહિતી સબમિટ કરો',
    'ITEMS': 'વસ્તુઓ',
    'AMOUNT': 'રકમ',
    'CANCEL ORDER': 'ઓર્ડર રદ કરો',
    'DISPATCH': 'રવાના',
    'WAITING FOR ADMIN': 'એડમિનની રાહ જોવાય છે',
    'Fleet Dispatch Actions': 'ફ્લીટ ડિસ્પેચ',
    'Orders approved by administration waiting for physical dispatch logs.': 'ઓર્ડર રવાના થવાની રાહ જોઈ રહ્યા છે.',
    'No Pending Dispatches': 'કોઈ પેન્ડિંગ ડિસ્પેચ નથી',
    'DATE': 'તારીખ',
    'REJECTION REASON': 'નકારવાનું કારણ',
    'Sales Registry': 'સેલ્સ રજિસ્ટ્રી',
    'Historical logs of your approvals, rejections, and closures.': 'મંજૂરી અને નકારવાના ઐતિહાસિક લોગ.',
    'No Records Found': 'કોઈ રેકોર્ડ મળ્યા નથી',
    'Filter History': 'ફિલ્ટર ઇતિહાસ',
    'Product Type': 'ઉત્પાદન પ્રકાર',
    'Date Range': 'તારીખ',
    'Apply Filters': 'ફિલ્ટર્સ લાગુ કરો',
    'Waiting >24h': 'રાહ >24કલાક',
    'SAVE': 'સાચવો',
    'Sales Queue': 'સેલ્સ કતાર',
    'My Monthly Targets': 'મારા માસિક લક્ષ્યો',
    'Volume (Tons)': 'વોલ્યુમ (ટન)',
    'Daily Visits': 'દૈનિક મુલાકાતો',
    'Pending Approvals': 'મંજૂરીઓ બાકી છે',
    'Outstanding Balances': 'બાકી બેલેન્સ',
    'Queue is Clear!': 'કતાર ખાલી છે!',
    'No orders currently awaiting your approval.': 'કોઈ ઓર્ડર બાકી નથી.',
    'Dealer': 'ડીલર',
    'Limit': 'મર્યાદા',
    'CONFIRM REJECT': 'નકારવાની ખાતરી કરો',
    'My Retailer Visits': 'મારી રિટેલર મુલાકાતો',
    'LOG NEW VISIT': 'નવી મુલાકાત નોંધો',
    'No Visits Logged': 'કોઈ મુલાકાતો નોંધાઈ નથી',
    'Log Visit': 'મુલાકાત નોંધો',
    'Retailer / Dealer': 'રિટેલર / ડીલર',
    'Visit Date (YYYY-MM-DD)': 'મુલાકાત તારીખ',
    'Remarks / Summary': 'રિમાર્કસ',
    'SAVE VISIT': 'મુલાકાત સાચવો',
    'Customer Ageing & Balances': 'ગ્રાહક એજિંગ',
    'Overview of outstanding balances and ageing buckets.': 'બાકી બેલેન્સ',
    'Has Outstanding': 'બાકી છે',
    'Export CSV': 'CSV નિકાસ કરો',
    'Reported Issues': 'નોંધાયેલ સમસ્યાઓ',
    'Issue:': 'સમસ્યા:',
    'Evidence:': 'પુરાવા:',
    'View Photo': 'ફોટો જુઓ',
    'Update Issue': 'સમસ્યા અપડેટ કરો',
    'Status': 'સ્થિતિ',
    'Resolution Notes': 'નિરાકરણ નોંધો',
    'Address': 'સરનામું',
    'PAN & GST': 'PAN અને GST',
    'Sales Rep': 'સેલ્સ પ્રતિનિધિ',
    'Total Orders': 'કુલ ઓર્ડર',
    'CREDIT LIMIT': 'ક્રેડિટ મર્યાદા',
    'SPENDABLE': 'વાપરી શકાય તેવું',
    'OUTSTANDING': 'બાકી',
    'Achieved:': 'પ્રાપ્ત:',
    'Target:': 'લક્ષ્ય:',
    'Delete': 'કાઢી નાખો',
    'Edit Details': 'વિગતો સંપાદિત કરો',
    'Place Order': 'ઓર્ડર આપો',
    'Start Date': 'પ્રારંભ તારીખ',
    'End Date': 'અંત તારીખ',
    'Name': 'નામ',
    'Company': 'કંપની',
    'Record Payment': 'ચુકવણી નોંધો',
    'Add Outstanding': 'બાકી ઉમેરો',
    'Edit Mode': 'એડિટ મોડ',
    'Unit': 'એકમ',
    'Unit Price (₹)': 'યુનિટ કિંમત',
    'Estimate Amount (₹)': 'અંદાજિત રકમ',
    'Auto Calculate': 'ઑટો ગણતરી',
    'Export Excel': 'એક્સેલ નિકાસ કરો',
    'Select Location': 'સ્થાન પસંદ કરો',
    'Previous': 'અગાઉના',
    'Next': 'આગળ',
    'Confirm Dispatch': 'ડિસ્પેચની ખાતરી કરો',
    'Mark Dispatched': 'રવાના માર્ક કરો',
    'Mark In Transit': 'ટ્રાન્ઝિટ માર્ક કરો',
    'Mark Delivered': 'ડિલિવર માર્ક કરો',
    'Cancel Order': 'ઓર્ડર રદ કરો',
    'Logistics & Delivery': 'લોજિસ્ટિક્સ અને ડિલિવરી',
    'Manage the physical dispatch and delivery of approved orders.': 'મંજૂર ઓર્ડર્સના ભૌતિક ડિસ્પેચનું સંચાલન કરો.',
    'No Active Logistics': 'કોઈ સક્રિય લોજિસ્ટિક્સ નથી',
    'There are no orders currently awaiting dispatch or delivery.': 'કોઈ ઓર્ડર ડિસ્પેચની રાહ જોતા નથી.',
    'Price': 'કિંમત',
    'Once marked Delivered, Customer must confirm receipt.': 'એકવાર ડિલિવર થયા પછી, ગ્રાહકે પુષ્ટિ કરવી પડશે.',
    'Dashboard': 'ડેશબોર્ડ',
    'Overview': 'વિહંગાવલોકન',
    'Admin Overview': 'એડમિન વિહંગાવલોકન',
    'My Orders': 'મારા ઓર્ડર',
    'Place Order': 'ઓર્ડર આપો',
    'New Order': 'નવો ઓર્ડર',
    'Invoices & Payments': 'ઇન્વોઇસ અને ચુકવણીઓ',
    'Report Issue': 'સમસ્યાની જાણ કરો',
    'Rewards & Targets': 'ઇનામો અને લક્ષ્યો',
    'Pending Approval': 'મંજૂરી બાકી છે',
    'My Visits': 'મારી મુલાકાતો',
    'Retailers Directory': 'રિટેલર્સ ડિરેક્ટરી',
    'Customers': 'ગ્રાહકો',
    'Dispatch Queue': 'ડિસ્પેચ કતાર',
    'Logistics': 'લોજિસ્ટિક્સ',
    'History': 'ઇતિહાસ',
    'Competitor Intel': 'હરીફ માહિતી',
    'Customer Ageing': 'ગ્રાહક એજિંગ',
    'Aging Report': 'એજિંગ રિપોર્ટ',
    'Reported Issues': 'નોંધાયેલ સમસ્યાઓ',
    'Issues': 'સમસ્યાઓ',
    'Pending Registrations': 'નોંધણી મંજૂરીઓ',
    'Customer Documents': 'ગ્રાહક દસ્તાવેજો',
    'Final Approvals': 'અંતિમ મંજૂરીઓ',
    'Admin Queue': 'એડમિન કતાર',
    'Challan Tracking': 'ચલણ ટ્રેકિંગ',
    'All Orders': 'બધા ઓર્ડર',
    'All Invoices': 'બધા ઇન્વોઇસ',
    'Import Data': 'ડેટા આયાત કરો',
    'Inventory & Pricing': 'ઇન્વેન્ટરી અને કિંમત',
    'Credit Management': 'ક્રેડિટ મેનેજમેન્ટ',
    'Outstanding Notes': 'બાકી નોંધો',
    'Team & Assignments': 'ટીમ અને કાર્યો',
    'Team': 'ટીમ',
    'Pending Invoices': 'બાકી ઇન્વોઇસ',
    'Credit Cycles': 'ક્રેડિટ સાયકલ',
    'Active Credit': 'સક્રિય ક્રેડિટ',
    'Edit Profile': 'પ્રોફાઇલ સંપાદિત કરો',
    'Profile': 'પ્રોફાઇલ',
    'Log Out': 'લૉગ આઉટ',
    'Sales Queue': 'સેલ્સ કતાર',
    'Sales Registry': 'સેલ્સ રજિસ્ટ્રી',

    'Log Visit': 'મુલાકાત નોંધો',
    'JPEG, PNG, JPG (Max 5MB)': 'JPEG, PNG, JPG (મહત્તમ 5MB)',
    'Gold Tier Trip (Dubai)': 'ગોલ્ડ ટિયર ટ્રીપ (દુબઈ)',
    'Silver Tier Trip': 'સિલ્વર ટિયર ટ્રીપ',
    'Ageing & Credit Overview': 'એજિંગ અને ક્રેડિટ વિહંગાવલોકન',
    'customer': 'ગ્રાહક',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [dynamicTranslations, setDynamicTranslations] = useState({});
  const fetchingKeys = useRef(new Set());

  useEffect(() => {
    const loadState = async () => {
      try {
        const savedLang = await AsyncStorage.getItem('user-language');
        if (savedLang) setLanguage(savedLang);
        
        // Load any previously auto-translated text from local cache
        const savedDynamic = await AsyncStorage.getItem('dynamic-translations-gu');
        if (savedDynamic) {
          setDynamicTranslations(JSON.parse(savedDynamic));
        }
      } catch (e) { }
    };
    loadState();
  }, []);

  const toggleLanguage = async () => {
    const nextLang = language === 'en' ? 'gu' : 'en';
    setLanguage(nextLang);
    try {
      await AsyncStorage.setItem('user-language', nextLang);
    } catch (e) { }
  };

  const fetchTranslationFallback = async (text) => {
    /* 
      SAFEST IMPLEMENTATION FOR EXPO:
      Do NOT call Google Translate directly from the frontend. 
      Even if you use EXPO_PUBLIC_API_KEY, the key gets embedded in the JS bundle and can be stolen.
      Instead, we call our own backend server, which securely holds the secret API key.
    */
    try {
      // NOTE: This assumes your backend server will eventually have this endpoint.
      // We wrap it in a safe try-catch so it won't break if the endpoint isn't ready yet.
      const response = await fetch(`${process.env.EXPO_PUBLIC_API_URL || 'http://10.0.2.2:3000/api'}/translate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, targetLanguage: 'gu' })
      });
      
      if (!response.ok) throw new Error('Backend translation failed or not implemented yet');
      
      const data = await response.json();
      return data.translatedText;
    } catch (error) {
      // Return a temporary marker or just the original text if the backend call fails
      console.log(`[Translation] Missing translation for: "${text}"`);
      return text; 
    }
  };

  const handleMissingTranslation = async (key) => {
    // Prevent duplicate network calls for the same missing string
    if (fetchingKeys.current.has(key)) return;
    fetchingKeys.current.add(key);

    const translatedText = await fetchTranslationFallback(key);
    
    // Only update state if the translation actually succeeded
    if (translatedText && translatedText !== key) {
      setDynamicTranslations(prev => {
        const updated = { ...prev, [key]: translatedText };
        // Cache the newly learned translation persistently
        AsyncStorage.setItem('dynamic-translations-gu', JSON.stringify(updated)).catch(() => {});
        return updated;
      });
    }
  };

  const t = (key) => {
    // Failsafe for empty or invalid keys
    if (!key || typeof key !== 'string') return key;

    if (language === 'gu') {
      // 1. Check hardcoded dictionary first (fastest)
      if (translations.gu[key]) {
        return translations.gu[key];
      }
      
      // 2. Check the dynamically loaded/cached dictionary
      if (dynamicTranslations[key]) {
        return dynamicTranslations[key];
      }
      
      // 3. Trigger automatic fallback in the background
      handleMissingTranslation(key);
    }
    
    // Always return the English text immediately if language is 'en', 
    // or as a temporary fallback while waiting for the background fetch to finish.
    return key;
  };

  /**
   * Helper specifically designed for dynamic backend content (descriptions, messages).
   * It uses the same cache-first system as t(), but adds safety filters to prevent
   * accidental translation of PII, IDs, URLs, or pure numeric values.
   */
  const tDynamic = (content) => {
    if (!content || typeof content !== 'string') return content;
    
    const trimmed = content.trim();
    if (trimmed.length === 0) return content;

    // Safety checks: Do not translate numbers, emails, or URLs
    if (/^[\d.,\s-]+$/.test(trimmed)) return content; // Pure numbers/formatting
    if (trimmed.includes('@') && trimmed.includes('.')) return content; // Likely an email
    if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) return content; // URLs
    if (/^[A-Za-z0-9_-]{10,}$/.test(trimmed) && !trimmed.includes(' ')) return content; // Likely a database ID

    // Fall back to the core cache-first translation engine
    return t(content);
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, tDynamic }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
